"""Remove Dummy Table

Revision ID: 47fbfa70564d
Revises: eb317f34f7e9
Create Date: 2024-06-17 11:52:51.454932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fbfa70564d'
down_revision = 'eb317f34f7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dumb', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
