"""Removed Student mock table in mydatabase.db

Revision ID: 99c01c546622
Revises: 47fbfa70564d
Create Date: 2024-06-17 13:05:48.099791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c01c546622'
down_revision = '47fbfa70564d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('roll', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('roll')
    )
    # ### end Alembic commands ###
